services:
  # Spring Boot Backend Service
  - type: web
    name: auca-csrs-backend
    runtime: docker
    dockerfilePath: ./csrs-backend/Dockerfile
    dockerContext: ./csrs-backend
    plan: free
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://uwiadeline389_db_user:Kiki%40%23123@cluster0.zgblg86.mongodb.net/csrs_db?retryWrites=true&w=majority&appName=Cluster0
