server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://uwiadeline389_db_user:Kiki%40%23123@cluster0.zgblg86.mongodb.net/csrs_db?retryWrites=true&w=majority&appName=Cluster0

# Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
