server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.mongodb.net/csrs_db?retryWrites=true&w=majority

# Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
